learningParams:
    seed: 1299777356020
# the length of tests and their number
    minTraceLength: 5
    maxTraceLength: 5
    maxNumTraces: 100
    sutInterface: sutinfo.yaml
# windows/freebsd/linux
    mapper: linux
tcpParams:
# number of times each query(test) is run, so as to
# add confidence that there were no missed/wrong responses
    runsPerQuery: 1
    confidence: 85
    sutPort: 18200
    sutIP: 127.0.0.1
    oracle: client
